[workspace]
resolver = "2"

members = ["day*"]
default-members = ["day*"]

[workspace.dependencies]
divan = "0.1.3"
nom_locate = "4.2.0"
nom-supreme = "0.8.0"
nom = "7.1.3"
rayon = "1.8.0"
lazy_static = "1.4"

